In [11]:
import numpy as np
import cv2 as cv
import glob


################ FIND CHESSBOARD CORNERS - OBJECT POINTS AND IMAGE POINTS #############################

chessboardSize = (7,10)
frameSize = (672,376)
# chessboardSize = (10,7)
# frameSize = (640,480)

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)


# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((chessboardSize[0] * chessboardSize[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:chessboardSize[0],0:chessboardSize[1]].T.reshape(-1,2)

size_of_chessboard_squares_mm = 25.4
objp = objp * size_of_chessboard_squares_mm

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpointsL = [] # 2d points in image plane.
imgpointsR = [] # 2d points in image plane.


imagesLeft = sorted(glob.glob('./left_calibration_images/*.jpg'))
imagesRight = sorted(glob.glob('./right_calibration_images/*.jpg'))
# imagesLeft = sorted(glob.glob('./stereoLeft_new/*.png'))
# imagesRight = sorted(glob.glob('./stereoRight_new/*.png'))

for imgLeft, imgRight in zip(imagesLeft, imagesRight):

    imgL = cv.imread(imgLeft)
    imgR = cv.imread(imgRight)
    grayL = cv.cvtColor(imgL, cv.COLOR_BGR2GRAY)
    grayR = cv.cvtColor(imgR, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    retL, cornersL = cv.findChessboardCorners(grayL, chessboardSize, None)
    retR, cornersR = cv.findChessboardCorners(grayR, chessboardSize, None)

    # If found, add object points, image points (after refining them)
    if retL and retR == True:

        objpoints.append(objp)

        cornersL = cv.cornerSubPix(grayL, cornersL, (11,11), (-1,-1), criteria)
        imgpointsL.append(cornersL)

        cornersR = cv.cornerSubPix(grayR, cornersR, (11,11), (-1,-1), criteria)
        imgpointsR.append(cornersR)

        # Draw and display the corners
        cv.drawChessboardCorners(imgL, chessboardSize, cornersL, retL)
        cv.imshow('img left', imgL)
        cv.drawChessboardCorners(imgR, chessboardSize, cornersR, retR)
        cv.imshow('img right', imgR)
        cv.waitKey(1000)


cv.destroyAllWindows()




############## CALIBRATION #######################################################

retL, cameraMatrixL, distL, rvecsL, tvecsL = cv.calibrateCamera(objpoints, imgpointsL, frameSize, None, None)
heightL, widthL, channelsL = imgL.shape
newCameraMatrixL, roi_L = cv.getOptimalNewCameraMatrix(cameraMatrixL, distL, (widthL, heightL), 1, (widthL, heightL))

retR, cameraMatrixR, distR, rvecsR, tvecsR = cv.calibrateCamera(objpoints, imgpointsR, frameSize, None, None)
heightR, widthR, channelsR = imgR.shape
newCameraMatrixR, roi_R = cv.getOptimalNewCameraMatrix(cameraMatrixR, distR, (widthR, heightR), 1, (widthR, heightR))



########## Stereo Vision Calibration #############################################

flags = 0
flags |= cv.CALIB_FIX_INTRINSIC
# Here we fix the intrinsic camara matrixes so that only Rot, Trns, Emat and Fmat are calculated.
# Hence intrinsic parameters are the same 

criteria_stereo= (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# This step is performed to transformation between the two cameras and calculate Essential and Fundamenatl matrix
retStereo, newCameraMatrixL, distL, newCameraMatrixR, distR, rot, trans, essentialMatrix, fundamentalMatrix = cv.stereoCalibrate(objpoints, imgpointsL, imgpointsR, newCameraMatrixL, distL, newCameraMatrixR, distR, grayL.shape[::-1], criteria_stereo, flags)


########## Stereo Rectification #################################################

rectifyScale= 1
rectL, rectR, projMatrixL, projMatrixR, Q, roi_L, roi_R= cv.stereoRectify(newCameraMatrixL, distL, newCameraMatrixR, distR, grayL.shape[::-1], rot, trans, rectifyScale,(0,0))

stereoMapL = cv.initUndistortRectifyMap(newCameraMatrixL, distL, rectL, projMatrixL, grayL.shape[::-1], cv.CV_16SC2)
stereoMapR = cv.initUndistortRectifyMap(newCameraMatrixR, distR, rectR, projMatrixR, grayR.shape[::-1], cv.CV_16SC2)

print("Saving parameters!")
cv_file = cv.FileStorage('stereoMap.xml', cv.FILE_STORAGE_WRITE)

print("Left Camera Intrinsic Matrix:\n", newCameraMatrixL)
print("Left Camera Distortion Coefficients:\n", distL)
print("Right Camera Intrinsic Matrix:\n", newCameraMatrixR)
print("Right Camera Distortion Coefficients:\n", distR)
print("Rotation Matrix (R):\n", rot)
print("Translation Vector (T):\n", trans)

cv_file.write('stereoMapL_x',stereoMapL[0])
cv_file.write('stereoMapL_y',stereoMapL[1])
cv_file.write('stereoMapR_x',stereoMapR[0])
cv_file.write('stereoMapR_y',stereoMapR[1])

cv_file.release()


Saving parameters!
Left Camera Intrinsic Matrix:
 [[380.03619385   0.         310.04739416]
 [  0.         135.65101624 118.61891106]
 [  0.           0.           1.        ]]
Left Camera Distortion Coefficients:
 [[-6.56798374e-01  2.22532772e+00 -1.60642589e-03  3.79290654e-02
  -3.22660274e+00]]
Right Camera Intrinsic Matrix:
 [[174.64897156   0.         184.71697986]
 [  0.         218.34190369 152.16174609]
 [  0.           0.           1.        ]]
Right Camera Distortion Coefficients:
 [[-0.82633059  1.16432527 -0.03274012 -0.01128613 -0.94503948]]
Rotation Matrix (R):
 [[ 0.90286898  0.05059515 -0.42692825]
 [-0.04743628  0.99871137  0.01803864]
 [ 0.42729076  0.00396536  0.90410557]]
Translation Vector (T):
 [[312.31859809]
 [-64.42551837]
 [ 48.83473781]]


In [12]:
baseline = np.linalg.norm(trans)
baseline # this is in the world coordinate frame

322.6118189789129

In [ ]:
secondary_focal_length = 257 
reference_focal_length = 196 # (avg of the fx & fy)
scaling_factor = secondary_focal_length/reference_focal_length
new_intrinsic_matrix_reference_camera = scaling_factor * newCameraMatrixR

print(new_intrinsic_matrix_reference_camera)