In [1]:
import yolov5
from pathlib import Path
import torch
from PIL import Image
import cv2

WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.utils' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.utils' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")



In [2]:
# or load custom model
model = yolov5.load('best.pt')

In [12]:
# set model parameters
model.conf = 0.40  # NMS confidence threshold
model.iou = 0.45  # NMS IoU threshold
model.agnostic = False  # NMS class-agnostic 
model.max_det = 1000  # maximum number of detections per image

In [13]:
# Load the image
img = Image.open("ball.jpg")

In [14]:
# Perform object detection
results = model(img)

In [15]:
# Get detected objects
detected_objects = results.pred[0]

In [21]:
detected_objects

tensor([[1.90817e+03, 1.11552e+03, 2.79927e+03, 2.03116e+03, 8.27478e-01, 0.00000e+00]], device='cuda:0')

In [35]:
boxes = detected_objects[:, :4] # x1, y1, x2, y2
scores = detected_objects[:, 4]
categories = detected_objects[:, 5]

In [36]:
boxes

tensor([[1908.17065, 1115.52258, 2799.26978, 2031.16089]], device='cuda:0')

In [32]:
boxes = boxes.squeeze(0)

In [33]:
center_x = (boxes[0] + boxes[2]) / 2
center_y = (boxes[1] + boxes[3]) / 2

In [34]:
center_x

tensor(2353.72021, device='cuda:0')

In [38]:
center_x = center_x.cpu()
center_x = center_x.numpy()

In [39]:
center_x

array(     2353.7, dtype=float32)

In [26]:
scores

tensor([0.82748], device='cuda:0')

In [27]:
categories

tensor([0.], device='cuda:0')

In [17]:
# Save the image with bounding boxes
img_with_boxes = results.render()[0]
img_with_boxes_pil = Image.fromarray(img_with_boxes)
img_with_boxes_pil.save('output_image.jpg')

Check on live video 

In [3]:
cap = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # results = model(frame)
# # Get detected objects
# detected_objects = results.pred[0]
# boxes = detected_objects[:, :4] # x1, y1, x2, y2
# scores = detected_objects[:, 4]
# categories = detected_objects[:, 5]
# boxes = boxes.squeeze(0)
    # img_with_boxes = results.render()[0]
    # Display the frame
    cv2.imshow('Live Video Feed', frame)

    # Exit the loop when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close the window
cap.release()
cv2.destroyAllWindows()

[ WARN:0@10.149] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@10.149] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range


error: OpenCV(4.7.0) /io/opencv/modules/highgui/src/window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [43]:
cap.release()
cv2.destroyAllWindows()